# Graph Based Neural Network

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.distributions as dist

from torch_geometric.nn import MessagePassing

class GraphNet(MessagePassing):
    def __init__(self):
        super(GraphNet, self).__init__(aggr = 'add')
        
    def forward(self, data, node_attr, edge_index, merger):
        return self.propagate(edge_index, data=data, node_attr=node_attr, merger=merger)
    
    def message(self, data_j, node_attr_i, node_attr_j, merger):
        print(data_j) 
        print(node_attr_i) 
        print(node_attr_j)
        return data_j

In [9]:
gnn = GraphNet()

In [10]:
x = torch.tensor([[[1.,2.],[3.,4.],[5.,6.]]])
y = torch.tensor([[[-1.,-2.],[-3.,-4.],[-5.,-6.]]])
edge_index = torch.tensor([[0, 0],
                           [1, 2]])
gnn(x, y, edge_index, 3)

tensor([[[1., 2.],
         [1., 2.]]])
tensor([[[-3., -4.],
         [-5., -6.]]])
tensor([[[-1., -2.],
         [-1., -2.]]])


tensor([[[0., 0.],
         [1., 2.],
         [1., 2.]]])